# -*- mode: ruby -*-
# vi: set ft=ruby :


VMS = [
  { :name => "router1" },
  { :name => "client1" },
  { :name => "server1" }
]


Vagrant.configure("2") do |config|

  config.vm.box = "b1-reseau"
  config.vbguest.auto_update = true
  config.vbguest.no_remote = false

  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  # config.vm.synced_folder "../data", "/vagrant_data"

  config.vm.provider "virtualbox" do |vb|
  
    # Display the VirtualBox GUI when booting the machine
    vb.gui = true
  
    # Customize the amount of memory on the VM:
    vb.memory = "512"
  
  end

  VMS.each do |node|
    config.vm.define node[:name] do |nodeconfig|
      config.vm.provider "virtualbox" do |vb|
         vb.name = "b1-tp4-#{node[:name]}"
      end
      nodeconfig.vm.hostname = "#{node[:name]}.tp4.b1"
 
      if node[:name] == "router1"
        nodeconfig.vm.network "private_network", ip: "10.1.0.254", netmask: "255.255.255.0", nic_type: "virtio", dhcp_enabled: false
        nodeconfig.vm.network "private_network", ip: "10.2.0.254", netmask: "255.255.255.0", nic_type: "virtio", dhcp_enabled: false
      
      elsif node[:name] == "client1"
        nodeconfig.vm.network "private_network", ip: "10.1.0.10", netmask: "255.255.255.0", nic_type: "virtio", dhcp_enabled: false
      
      elsif node[:name] == "server1"
        nodeconfig.vm.network "private_network", ip: "10.2.0.10", netmask: "255.255.255.0", nic_type: "virtio", dhcp_enabled: false

      end
      nodeconfig.vm.provision "shell", path: "./data/scripts/#{node[:name]}/startup.sh"
    end
  end

end
